project:
  type: website

website:
  navbar:
    background: green
    foreground: white
    left:
      - about.qmd
      - href: index.qmd
        text: Technical Writing Portfolio
      - guides.qmd
      - href: "training guides.qmd"
        text: Strength Training Guides

  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



