project:
  type: website

website:
  title: "Ilona Silverwood"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guides.qmd
      - index.qmd
  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



