project:
  type: website

website:
  title: "Ilona Silverwood"
  navbar:
    left:
      - href: index.qmd
        text: Technical Writing Portfolio
      - about.qmd
      - guides.qmd

  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



