# Bracing

Bracing is the act of stiffening the muscles that make up your abdominal wall. It is neither pulling your abs in (also called hollowing), nor actively pushing them out. Your goal is to contract the muscles in order to enhance spinal stability. 


## Why bracing is important

An appropriate amount of abdominal stiffness enhances athletic performance by: 

* Allowing a greater load to be lifted.
* Eliminating spinal movement that could result in discomfort.
* Increasing speed and force generation at the shoulder and hip.


## When to brace

Different situations call for different levels of stiffness through the abdominal wall. A near-max lift will require a much stronger brace than a lighter lift. You should be matching the intensity of the brace to the given activity, generating enough stiffness to ensure that the added load will not result in unnecessary torso movement during the activity.



## How to brace

Developing the muscle control necessary to create abdominal stiffness might require practice. The following steps will allow you to practice finding the appropriate muscular pattern:

1. Stand upright, in a neutral position. Do not let your shoulders or head fall forward.
2. Place your thumbs on your spinal extensors near the curve of your lower back.
3. Wrap fingers around your sides, towards your belly button.
4. Without moving, stiffen your abdominal muscles until you feel the muscles in both the front and back stiffen.

If this feels foreign, practice with other limbs first. 

1. Let your arm hang straight at your side.
2. Contract your bicep and tricep at the same time.
3. Note the difference in how the area feels, despite the lack of movement at the shoulder or elbow. 

# Hip hinge

A hip hinge is a cycle of [hip flexion] and [hip extension], usually performed while standing. 


## Why hip hinging is important

The hips are designed to produce force, while the spine is not. Effective strength training requires us to generate force using the hips, while the lower back stays in a relatively fixed position due to an appropriate [brace]. It is important to be able to differentiate between movement at the hip and the lower back for several reasons:

* increase the amount of load you can lift safely
* reduce risk of low back discomfort
* increase [hip extensor muscle] strength
* encourage hypertrophy in hip extensors


## When to hip hinge

Every compound lower body movement requires some degree of hip hinging. Some movements, for example a [Romanian deadlift], are entirely hip hinge based. Others, like a [squat] or [lunge], require a combination of hip hinging and [knee flexion]. The degree of hip movement relative to knee movement in a given exercise may change depending on:

* the variation you are performing
* your individual anatomy and preference
* your training goals


## How to hip hinge

Hip hinging may feel foreign at first, and it might be challenging to feel the difference between bending at the hip and bending at the lower back. Monitoring your movement by recording yourself or using your hands to feel what your back and hips are doing will help you learn the hip hinge pattern. To get started, try the following drill:

1. Stand upright, in a [neutral position].
2. [Brace] abdominal wall.
3. Place one palm on your stomach and the other on your lower back.
4. Maintain the abdominal brace as you push your hips back.
    * NOTE: pay attention to your hands. If you feel your torso bending forward, reset the movement and try again.
5. Once you have reached your maximum range of motion, keep your torso still as your hips push forward to standing upright. 
    * NOTE: End range of motion is the point where you cannot move the hips back any more without bending at the spine.






