project:
  type: website
  output-dir: docs

website:
  title: "Ilona Silverwood: Technical Writing Profile and Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - text: About Me
      - guides.qmd
      - index.qmd
  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



