project:
  type: website
  output-dir: docs

website:
  title: "Ilona Silverwood"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guides.qmd
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



